name: Copy texfiles to website repository

on:
  workflow_dispatch:
    inputs:
      commit_message:
        description: 'Messaggio di commit manuale'
        required: true
        default: 'Update texfiles'

jobs:
  copy-texfiles:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout MultilinearVerseLatex repository
      uses: actions/checkout@v4
      with:
        path: MultilinearVerseLatex

    - name: Checkout MultilinearVerse repository
      uses: actions/checkout@v2
      with:
        repository: aleianno90/MultilinearVerse
        path: MultilinearVerse
        token: ${{ secrets.MULTILINEAR_VERSE_TOKEN }}

    - name: Copy texfiles folder
      run: |
        cd MultilinearVerse
        git fetch
        git checkout latex-contribution
        cd texfiles && ls | grep -v 'tags' | xargs rm -rf && cd ..
        cd ..
        cp -rf MultilinearVerseLatex/texfiles/* MultilinearVerse/texfiles

    - name: Commit and push changes
      run: |
        cd MultilinearVerse
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git add texfiles
        git commit -m "${{ github.event.inputs.commit_message }}"
        git push
