name: Copy texfiles to website repository

on:
  pull_request:
    branches: [master]
    types: [closed]
    paths:
      - 'texfiles/**'

jobs:
  copy-texfiles:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout MultilinearVerseLatex repository
      uses: actions/checkout@v2
      with:
        path: MultilinearVerseLatex

    - name: Checkout MultilinearVerse repository
      uses: actions/checkout@v2
      with:
        repository: aleianno90/MultilinearVerse
        path: MultilinearVerse
        token: ${{ secrets.MULTILINEAR_VERSE_TOKEN || github.token }}

    - name: Copy texfiles folder
      run: |
        cd MultilinearVerse
        git fetch
        git checkout latex-contribution
        cd texfiles && ls | grep -v 'tags' | xargs rm -rf && cd ..
        cd ..
        cp -rf MultilinearVerseLatex/texfiles/* MultilinearVerse/texfiles

    - name: Commit and push changes
      run: |
        cd MultilinearVerse
        git config user.name "${{ github.event.pull_request.user.login }}"
        git config user.email "${{ github.event.pull_request.user.email }}"
        git add texfiles
        git commit -m "Update texfiles with commit: ${{ github.event.pull_request.title }}"
        git push
